name: test-app-53
version: 0.1
summary: hello world
description: |
  simple python hello world
base: core18
grade: devel
confinement: devmode


parts:
  test-app-53:
    plugin: python
    python-version: python2
    source: .
    

apps:
  test-app-53:
    command: bin/test-app-53