name: deci53 # you probably want to 'snapcraft register <name>'
version: '4.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: Single-line elevator pitch for your amazing snap # 79 char long summary
description: |
  This is my-snap's description. You have a paragraph or two to tell the
  most important story about your snap. Keep it under 100 words though,
  we live in tweetspace and your description wants to look good in the snap
  store.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  deci53:
    command: bin/wrapper
    plugs: [opengl, x11, unity7, system-observe, hidraw, locale-control, gsettings, pulseaudio, wayland, network, network-bind, home, desktop, desktop-legacy]

parts:
  move-src:
    plugin: dump
    source: .
    organize:
      main.py: bin/deci53
      wrapper: bin/wrapper

  kivy:
    plugin: python
    python-version: 'python3'
    python-packages:
        - cryptoauthlib
        - setuptools
        - kivy
        - Cython
    stage-packages:
      # - python3-kivy
      - libmtdev1
      - libmtdev-dev
      - libgl1-mesa-dri
      - libgl1-mesa-glx
      - libglew1.13
      - cython3
    build-packages: 
      - python3-kivy
