name: deci53
version: 0.1
summary: hello world
description: |
  simple python hello world
base: core18
grade: devel
confinement: devmode


parts:
  deci53:
    plugin: python
    python-version: python2
    source: .
